version: "3.9"

services:
  nlp-service:
    build:
      context: ./nlp_service
    container_name: nlp-service
    environment:
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    restart: unless-stopped

  ai-secretary-app:
    build:
      context: ./ai-secretary-app
    container_name: ai-secretary-app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_WHISPER_MODEL=${OPENAI_WHISPER_MODEL:-whisper-1}
      - OPENAI_WHISPER_LANGUAGE=${OPENAI_WHISPER_LANGUAGE:-}
      - OPENAI_ORGANIZATION=${OPENAI_ORGANIZATION:-}
      - OPENAI_PROJECT=${OPENAI_PROJECT:-}
      - OPENAI_REQUEST_TIMEOUT_MS=${OPENAI_REQUEST_TIMEOUT_MS:-180000}
      - NLP_SERVICE_URL=http://nlp-service:8000
      - NLP_SERVICE_REQUEST_TIMEOUT_MS=45000
      - NLP_SERVICE_RETRY_COUNT=2
      - JIRA_REQUEST_TIMEOUT_MS=45000
      - NEXT_PUBLIC_JIRA_DEFAULT_BASE_URL=
    ports:
      - "3000:3000"
    depends_on:
      - nlp-service
    restart: unless-stopped
